/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    classes: Class;
    specs: Spec;
    versions: Version;
    macros: Macro;
    guides: Guide;
    articles: Article;
    pages: Page;
    'credit-packages': CreditPackage;
    'credit-orders': CreditOrder;
    'macro-exchanges': MacroExchange;
    'credit-transactions': CreditTransaction;
    tickets: Ticket;
    'ticket-messages': TicketMessage;
    notifications: Notification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    specs: SpecsSelect<false> | SpecsSelect<true>;
    versions: VersionsSelect<false> | VersionsSelect<true>;
    macros: MacrosSelect<false> | MacrosSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'credit-packages': CreditPackagesSelect<false> | CreditPackagesSelect<true>;
    'credit-orders': CreditOrdersSelect<false> | CreditOrdersSelect<true>;
    'macro-exchanges': MacroExchangesSelect<false> | MacroExchangesSelect<true>;
    'credit-transactions': CreditTransactionsSelect<false> | CreditTransactionsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    'ticket-messages': TicketMessagesSelect<false> | TicketMessagesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  avatar?: (number | null) | Media;
  /**
   * 只有超级管理员可以修改角色
   */
  role: 'super-admin' | 'operator' | 'support' | 'user';
  oauthProvider?: ('google' | 'github') | null;
  oauthId?: string | null;
  /**
   * 新用户默认 20 积分
   */
  credits?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  slug: string;
  nameZh: string;
  nameEn: string;
  /**
   * 例如 #C69B6D
   */
  color: string;
  icon?: (number | null) | Media;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specs".
 */
export interface Spec {
  id: number;
  slug: string;
  nameZh: string;
  nameEn: string;
  class: number | Class;
  role: 'tank' | 'healer' | 'melee-dps' | 'ranged-dps';
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versions".
 */
export interface Version {
  id: number;
  label: string;
  codename?: string | null;
  releasedAt?: string | null;
  isCurrent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "macros".
 */
export interface Macro {
  id: number;
  title: string;
  /**
   * 留空将根据名称自动生成
   */
  slug: string;
  /**
   * 普通宏建议 5 积分，高级宏建议 50 积分
   */
  tier: 'regular' | 'premium';
  price: number;
  /**
   * 0 = 永久有效
   */
  durationDays: number;
  autoRenewable?: boolean | null;
  summary?: string | null;
  previewImg?: (number | null) | Media;
  demoVideoUrl?: string | null;
  classes?: (number | Class)[] | null;
  specs?: (number | Spec)[] | null;
  versions?: (number | Version)[] | null;
  tags?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 此字段对未兑换用户将自动返回 null
   */
  codeContent?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  /**
   * 排序权重，数值越小越靠前
   */
  weight?: number | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  category?: ('announcement' | 'blog' | 'changelog') | null;
  /**
   * 置顶
   */
  pinned?: boolean | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-packages".
 */
export interface CreditPackage {
  id: number;
  /**
   * 例如：充值 100 元得 110 积分
   */
  label: string;
  amount: number;
  /**
   * 例如充 100 元送 10 积分，则填 110
   */
  creditsGranted: number;
  /**
   * 在 DodoPayments 后台创建的对应价格产品 ID
   */
  dodoProductId: string;
  currency: 'CNY' | 'USD';
  enabled?: boolean | null;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-orders".
 */
export interface CreditOrder {
  id: number;
  orderNumber: string;
  user: number | User;
  amount: number;
  currency: 'CNY' | 'USD';
  creditsGranted: number;
  status: 'pending' | 'paid' | 'failed';
  /**
   * DodoPayments checkout session ID
   */
  dodoCheckoutId?: string | null;
  paidAt?: string | null;
  /**
   * 调试用
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "macro-exchanges".
 */
export interface MacroExchange {
  id: number;
  user: number | User;
  macro: number | Macro;
  creditsSpent: number;
  grantedAt?: string | null;
  /**
   * 留空 = 永久有效
   */
  expiresAt?: string | null;
  autoRenew?: boolean | null;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions".
 */
export interface CreditTransaction {
  id: number;
  user: number | User;
  /**
   * 正数=增加，负数=减少
   */
  amount: number;
  balanceAfter: number;
  type: 'register_bonus' | 'recharge' | 'exchange' | 'renew' | 'refund' | 'admin_adjust';
  relatedOrder?: (number | null) | CreditOrder;
  relatedExchange?: (number | null) | MacroExchange;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  subject: string;
  user: number | User;
  status: 'open' | 'in-progress' | 'resolved' | 'closed';
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  category?: ('refund' | 'usage' | 'account' | 'feedback' | 'other') | null;
  relatedMacro?: (number | null) | Macro;
  relatedOrder?: (number | null) | CreditOrder;
  assignee?: (number | null) | User;
  closedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-messages".
 */
export interface TicketMessage {
  id: number;
  ticket: number | Ticket;
  sender: number | User;
  senderType: 'user' | 'staff';
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  attachments?:
    | {
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 只有客服之间可见
   */
  isInternalNote?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  title: string;
  body?: string | null;
  /**
   * 点击通知后跳转的站内链接
   */
  link?: string | null;
  category?: ('system' | 'order' | 'ticket' | 'promotion') | null;
  read?: boolean | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'specs';
        value: number | Spec;
      } | null)
    | ({
        relationTo: 'versions';
        value: number | Version;
      } | null)
    | ({
        relationTo: 'macros';
        value: number | Macro;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'credit-packages';
        value: number | CreditPackage;
      } | null)
    | ({
        relationTo: 'credit-orders';
        value: number | CreditOrder;
      } | null)
    | ({
        relationTo: 'macro-exchanges';
        value: number | MacroExchange;
      } | null)
    | ({
        relationTo: 'credit-transactions';
        value: number | CreditTransaction;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'ticket-messages';
        value: number | TicketMessage;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  oauthProvider?: T;
  oauthId?: T;
  credits?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  slug?: T;
  nameZh?: T;
  nameEn?: T;
  color?: T;
  icon?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specs_select".
 */
export interface SpecsSelect<T extends boolean = true> {
  slug?: T;
  nameZh?: T;
  nameEn?: T;
  class?: T;
  role?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versions_select".
 */
export interface VersionsSelect<T extends boolean = true> {
  label?: T;
  codename?: T;
  releasedAt?: T;
  isCurrent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "macros_select".
 */
export interface MacrosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tier?: T;
  price?: T;
  durationDays?: T;
  autoRenewable?: T;
  summary?: T;
  previewImg?: T;
  demoVideoUrl?: T;
  classes?: T;
  specs?: T;
  versions?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  body?: T;
  codeContent?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  weight?: T;
  cover?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  category?: T;
  pinned?: T;
  cover?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-packages_select".
 */
export interface CreditPackagesSelect<T extends boolean = true> {
  label?: T;
  amount?: T;
  creditsGranted?: T;
  dodoProductId?: T;
  currency?: T;
  enabled?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-orders_select".
 */
export interface CreditOrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  amount?: T;
  currency?: T;
  creditsGranted?: T;
  status?: T;
  dodoCheckoutId?: T;
  paidAt?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "macro-exchanges_select".
 */
export interface MacroExchangesSelect<T extends boolean = true> {
  user?: T;
  macro?: T;
  creditsSpent?: T;
  grantedAt?: T;
  expiresAt?: T;
  autoRenew?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions_select".
 */
export interface CreditTransactionsSelect<T extends boolean = true> {
  user?: T;
  amount?: T;
  balanceAfter?: T;
  type?: T;
  relatedOrder?: T;
  relatedExchange?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  subject?: T;
  user?: T;
  status?: T;
  priority?: T;
  category?: T;
  relatedMacro?: T;
  relatedOrder?: T;
  assignee?: T;
  closedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-messages_select".
 */
export interface TicketMessagesSelect<T extends boolean = true> {
  ticket?: T;
  sender?: T;
  senderType?: T;
  body?: T;
  attachments?:
    | T
    | {
        file?: T;
        id?: T;
      };
  isInternalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  title?: T;
  body?: T;
  link?: T;
  category?: T;
  read?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}