/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    classes: Class;
    specs: Spec;
    versions: Version;
    macros: Macro;
    guides: Guide;
    articles: Article;
    pages: Page;
    'credit-packages': CreditPackage;
    'credit-orders': CreditOrder;
    'macro-exchanges': MacroExchange;
    'credit-transactions': CreditTransaction;
    tickets: Ticket;
    'ticket-messages': TicketMessage;
    notifications: Notification;
    'plugin-files': PluginFile;
    'plugin-releases': PluginRelease;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    specs: SpecsSelect<false> | SpecsSelect<true>;
    versions: VersionsSelect<false> | VersionsSelect<true>;
    macros: MacrosSelect<false> | MacrosSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'credit-packages': CreditPackagesSelect<false> | CreditPackagesSelect<true>;
    'credit-orders': CreditOrdersSelect<false> | CreditOrdersSelect<true>;
    'macro-exchanges': MacroExchangesSelect<false> | MacroExchangesSelect<true>;
    'credit-transactions': CreditTransactionsSelect<false> | CreditTransactionsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    'ticket-messages': TicketMessagesSelect<false> | TicketMessagesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'plugin-files': PluginFilesSelect<false> | PluginFilesSelect<true>;
    'plugin-releases': PluginReleasesSelect<false> | PluginReleasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  avatar?: (number | null) | Media;
  /**
   * 只有超级管理员可以修改角色
   */
  role: 'super-admin' | 'operator' | 'support' | 'user';
  oauthProvider?: ('google' | 'github') | null;
  oauthId?: string | null;
  /**
   * 新用户默认 20 积分
   */
  credits?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * 媒体库：图片、视频、PDF。已建预览图、卡片、封面、社交分享四个尺寸。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  slug: string;
  nameZh: string;
  nameEn: string;
  /**
   * 例如 #C69B6D
   */
  color: string;
  icon?: (number | null) | Media;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specs".
 */
export interface Spec {
  id: number;
  slug: string;
  nameZh: string;
  nameEn: string;
  class: number | Class;
  role: 'tank' | 'healer' | 'melee-dps' | 'ranged-dps';
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versions".
 */
export interface Version {
  id: number;
  label: string;
  codename?: string | null;
  releasedAt?: string | null;
  isCurrent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 魔兽世界宏代码商品。普通宏建议 5 积分、高级宏 100 积分；代码字段对未兑换用户自动隐藏。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "macros".
 */
export interface Macro {
  id: number;
  title: string;
  /**
   * 留空将根据名称自动生成，影响前台 URL
   */
  slug: string;
  /**
   * 普通宏建议 5 积分，高级宏建议 100 积分
   */
  tier: 'regular' | 'premium';
  /**
   * 0 = 免费宏（用户无需兑换即可查看代码）
   */
  price?: number | null;
  /**
   * 0 = 永久有效。仅付费宏需要
   */
  durationDays?: number | null;
  /**
   * 仅在付费且有期限时有意义
   */
  autoRenewable?: boolean | null;
  /**
   * 勾选后在首页"精选宏包"区显示
   */
  isFeatured?: boolean | null;
  /**
   * 数值越小越靠前
   */
  featuredOrder?: number | null;
  /**
   * 一句话描述用途，会在列表卡片、SEO meta、社交分享中使用
   */
  summary: string;
  /**
   * 建议尺寸 1600x900，会自动生成卡片/封面/OG 图多个尺寸
   */
  previewImg?: (number | null) | Media;
  /**
   * 支持 YouTube / Bilibili / 直链 MP4，留空则不显示
   */
  demoVideoUrl?: string | null;
  classes?: (number | Class)[] | null;
  specs?: (number | Spec)[] | null;
  versions?: (number | Version)[] | null;
  /**
   * 便于前台筛选和聚合，例如：单体输出、群体输出、保命、控场、自我治疗
   */
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 此字段对未兑换用户自动返回 null。新建草稿时也会被隐藏，正常发布后由购买者自动可见。
   */
  codeContent?: string | null;
  /**
   * 搜索引擎与社交分享时使用，留空则回落到名称/简介/预览图
   */
  seo?: {
    /**
     * 默认使用宏名称 + 站名
     */
    seoTitle?: string | null;
    /**
     * 默认使用简介
     */
    seoDescription?: string | null;
    /**
     * 建议 1200x630，留空则使用预览图
     */
    ogImage?: (number | null) | Media;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 新手教程与使用指南。weight 越小越靠前。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  /**
   * 排序权重，数值越小越靠前
   */
  weight?: number | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 站内文章：公告、博客、更新日志。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  category?: ('announcement' | 'blog' | 'changelog') | null;
  /**
   * 置顶
   */
  pinned?: boolean | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 独立页面（关于、联系、隐私政策等）。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 积分充值档次配置。可设置原价、优惠标签和角标，用于前台营销展示。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-packages".
 */
export interface CreditPackage {
  id: number;
  /**
   * 例如：充值 100 元得 110 积分
   */
  label: string;
  amount: number;
  /**
   * 划线显示的原价，需大于实际售价才有效果
   */
  originalAmount?: number | null;
  /**
   * 例如充 100 元送 10 积分，则填 110
   */
  creditsGranted: number;
  /**
   * 如：限时8折、首充特惠、VIP专享
   */
  discountLabel?: string | null;
  badge?: ('none' | 'hot' | 'recommended' | 'new') | null;
  /**
   * 在 DodoPayments 后台创建的对应价格产品 ID
   */
  dodoProductId: string;
  currency: 'CNY' | 'USD';
  enabled?: boolean | null;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 充值订单。仅由支付 webhook 程序化创建，财务字段在后台只读以保护对账完整性。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-orders".
 */
export interface CreditOrder {
  id: number;
  orderNumber: string;
  user: number | User;
  /**
   * 财务数据不可修改
   */
  amount: number;
  currency: 'CNY' | 'USD';
  /**
   * 财务数据不可修改
   */
  creditsGranted: number;
  status: 'pending' | 'paid' | 'failed';
  /**
   * DodoPayments checkout session ID
   */
  dodoCheckoutId?: string | null;
  paidAt?: string | null;
  /**
   * 调试用，请勿手动修改
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 宏兑换记录。每条记录表示一个用户用积分解锁了某个宏。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "macro-exchanges".
 */
export interface MacroExchange {
  id: number;
  user: number | User;
  macro: number | Macro;
  /**
   * 兑换后不可修改，避免破坏对账
   */
  creditsSpent: number;
  grantedAt?: string | null;
  /**
   * 留空 = 永久有效
   */
  expiresAt?: string | null;
  autoRenew?: boolean | null;
  /**
   * 设置后该兑换记录将不再授予访问权限
   */
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 积分流水。仅由系统程序化创建，所有字段只读，用作对账依据。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions".
 */
export interface CreditTransaction {
  id: number;
  /**
   * 系统自动生成的列表显示标题
   */
  label?: string | null;
  user: number | User;
  /**
   * 正数=增加，负数=减少
   */
  amount: number;
  balanceAfter: number;
  type: 'register_bonus' | 'recharge' | 'exchange' | 'renew' | 'refund' | 'admin_adjust';
  relatedOrder?: (number | null) | CreditOrder;
  relatedExchange?: (number | null) | MacroExchange;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 用户提交的客服工单。员工可指派、回复、变更优先级和状态。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  subject: string;
  user: number | User;
  status: 'open' | 'in-progress' | 'resolved' | 'closed';
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  category?: ('refund' | 'usage' | 'account' | 'feedback' | 'other') | null;
  relatedMacro?: (number | null) | Macro;
  relatedOrder?: (number | null) | CreditOrder;
  assignee?: (number | null) | User;
  closedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 工单消息。每条消息可标记为内部备注（用户不可见）。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-messages".
 */
export interface TicketMessage {
  id: number;
  /**
   * 系统自动生成的列表显示标题，方便客服快速识别消息内容
   */
  label?: string | null;
  ticket: number | Ticket;
  sender: number | User;
  senderType: 'user' | 'staff';
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  attachments?:
    | {
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * ⚠️ 警告：勾选后该消息只有客服之间可见，绝不会发送给提交工单的用户。请仔细确认！
   */
  isInternalNote?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 站内通知。可按系统、订单、工单、促销分类。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  title: string;
  body?: string | null;
  /**
   * 点击通知后跳转的站内链接
   */
  link?: string | null;
  category?: ('system' | 'order' | 'ticket' | 'promotion') | null;
  read?: boolean | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 插件文件上传库，支持 .zip 等压缩包格式。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-files".
 */
export interface PluginFile {
  id: number;
  description?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * 插件版本管理：上传文件或提供云盘链接。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-releases".
 */
export interface PluginRelease {
  id: number;
  /**
   * 例如 v1.2.0
   */
  version: string;
  changelog?: string | null;
  /**
   * 格式 YYYY-MM-DD
   */
  publishedAt: string;
  /**
   * 发布后前台可见
   */
  isPublished?: boolean | null;
  deliveryMode: 'file' | 'link';
  /**
   * 上传 .zip 等插件压缩包
   */
  pluginFile?: (number | null) | PluginFile;
  /**
   * 例如百度网盘、夸克网盘等分享链接
   */
  cloudUrl?: string | null;
  /**
   * 如有提取码请填写
   */
  cloudPassword?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'specs';
        value: number | Spec;
      } | null)
    | ({
        relationTo: 'versions';
        value: number | Version;
      } | null)
    | ({
        relationTo: 'macros';
        value: number | Macro;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'credit-packages';
        value: number | CreditPackage;
      } | null)
    | ({
        relationTo: 'credit-orders';
        value: number | CreditOrder;
      } | null)
    | ({
        relationTo: 'macro-exchanges';
        value: number | MacroExchange;
      } | null)
    | ({
        relationTo: 'credit-transactions';
        value: number | CreditTransaction;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'ticket-messages';
        value: number | TicketMessage;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'plugin-files';
        value: number | PluginFile;
      } | null)
    | ({
        relationTo: 'plugin-releases';
        value: number | PluginRelease;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  oauthProvider?: T;
  oauthId?: T;
  credits?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  slug?: T;
  nameZh?: T;
  nameEn?: T;
  color?: T;
  icon?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specs_select".
 */
export interface SpecsSelect<T extends boolean = true> {
  slug?: T;
  nameZh?: T;
  nameEn?: T;
  class?: T;
  role?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versions_select".
 */
export interface VersionsSelect<T extends boolean = true> {
  label?: T;
  codename?: T;
  releasedAt?: T;
  isCurrent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "macros_select".
 */
export interface MacrosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tier?: T;
  price?: T;
  durationDays?: T;
  autoRenewable?: T;
  isFeatured?: T;
  featuredOrder?: T;
  summary?: T;
  previewImg?: T;
  demoVideoUrl?: T;
  classes?: T;
  specs?: T;
  versions?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  body?: T;
  codeContent?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  weight?: T;
  cover?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  category?: T;
  pinned?: T;
  cover?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-packages_select".
 */
export interface CreditPackagesSelect<T extends boolean = true> {
  label?: T;
  amount?: T;
  originalAmount?: T;
  creditsGranted?: T;
  discountLabel?: T;
  badge?: T;
  dodoProductId?: T;
  currency?: T;
  enabled?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-orders_select".
 */
export interface CreditOrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  amount?: T;
  currency?: T;
  creditsGranted?: T;
  status?: T;
  dodoCheckoutId?: T;
  paidAt?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "macro-exchanges_select".
 */
export interface MacroExchangesSelect<T extends boolean = true> {
  user?: T;
  macro?: T;
  creditsSpent?: T;
  grantedAt?: T;
  expiresAt?: T;
  autoRenew?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions_select".
 */
export interface CreditTransactionsSelect<T extends boolean = true> {
  label?: T;
  user?: T;
  amount?: T;
  balanceAfter?: T;
  type?: T;
  relatedOrder?: T;
  relatedExchange?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  subject?: T;
  user?: T;
  status?: T;
  priority?: T;
  category?: T;
  relatedMacro?: T;
  relatedOrder?: T;
  assignee?: T;
  closedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-messages_select".
 */
export interface TicketMessagesSelect<T extends boolean = true> {
  label?: T;
  ticket?: T;
  sender?: T;
  senderType?: T;
  body?: T;
  attachments?:
    | T
    | {
        file?: T;
        id?: T;
      };
  isInternalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  title?: T;
  body?: T;
  link?: T;
  category?: T;
  read?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-files_select".
 */
export interface PluginFilesSelect<T extends boolean = true> {
  description?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-releases_select".
 */
export interface PluginReleasesSelect<T extends boolean = true> {
  version?: T;
  changelog?: T;
  publishedAt?: T;
  isPublished?: T;
  deliveryMode?: T;
  pluginFile?: T;
  cloudUrl?: T;
  cloudPassword?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * 全局运营配置：充值页面文案、活动横幅、充值须知等。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * 控制前台 /credits 页面的标题、副标题、活动横幅与充值须知。
   */
  creditPage?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * 开启后在页面顶部显示活动横幅条
     */
    promoEnabled?: boolean | null;
    /**
     * 例如：新用户首充双倍积分、限时全场8折
     */
    promoBanner?: string | null;
    noticeEnabled?: boolean | null;
    /**
     * 留空则使用系统默认充值须知
     */
    notice?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  creditPage?:
    | T
    | {
        title?: T;
        subtitle?: T;
        promoEnabled?: T;
        promoBanner?: T;
        noticeEnabled?: T;
        notice?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}